pipeline {
    agent any
    
    environment {
        APP_NAME = "nodejs-devops-app"
        REGISTRY_USER = "vinod223" 
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        FULL_IMAGE = "${env.REGISTRY_USER}/${env.APP_NAME}:${env.IMAGE_TAG}"
        
        // AWS & Docker Hub Credentials from Jenkins UI
        DOCKER_HUB_CREDS      = credentials('docker-hub-creds')
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
        
        // This must match the 'key_name' in your variables.tf
        KEY_NAME = "nodeapp_key" 
    }

    stages {
        stage('Infrastructure Provisioning') {
            steps {
                script {
                    // Initialize and build AWS infrastructure
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                    
                    // DYNAMICALLY capture the IP address from Terraform
                    env.TARGET_IP = sh(script: "terraform output -raw public_ip", returnStdout: true).trim()
                    echo "Infrastructure Ready. Target IP: ${env.TARGET_IP}"
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                // Building from the /app directory as per your structure
                sh "docker build -t ${env.FULL_IMAGE} ./app"
                sh "docker tag ${env.FULL_IMAGE} ${env.REGISTRY_USER}/${env.APP_NAME}:latest"
                
                sh "echo ${env.DOCKER_HUB_CREDS_PSW} | docker login -u ${env.DOCKER_HUB_CREDS_USR} --password-stdin"
                sh "docker push ${env.FULL_IMAGE}"
                sh "docker push ${env.REGISTRY_USER}/${env.APP_NAME}:latest"
            }
        }

        stage('Security Scan') {
            steps {
                // Trivy scan is a major plus for your assessment
                sh "trivy image ${env.FULL_IMAGE} || true"
            }
        }

        stage('Remote Deploy') {
            steps {
                script {
                    // Path to the .pem file generated by Terraform's local_file resource
                    def privateKeyPath = "${env.WORKSPACE}/${env.KEY_NAME}.pem"
                    
                    // Give AWS a moment to initialize the SSH service and run UserData
                    echo "Waiting 60 seconds for EC2 initialization..."
                    sleep 60 

                    // We use 'retry' to handle AWS SSH warm-up time
                    retry(5) {
                        sshagent(credentials: []) {
                            sh """
                            ssh -i ${privateKeyPath} -o StrictHostKeyChecking=no ubuntu@${env.TARGET_IP} << 'EOF'
                                # Login to Docker Hub on Remote EC2
                                echo "${env.DOCKER_HUB_CREDS_PSW}" | sudo docker login -u "${env.DOCKER_HUB_CREDS_USR}" --password-stdin
                                
                                # Deploy Container
                                sudo docker pull ${env.REGISTRY_USER}/${env.APP_NAME}:latest
                                sudo docker stop nodejs_app || true
                                sudo docker rm nodejs_app || true
                                sudo docker run -d --name nodejs_app -p 3000:3000 ${env.REGISTRY_USER}/${env.APP_NAME}:latest
EOF
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up the local Docker image and the sensitive .pem file
            sh "docker rmi ${env.FULL_IMAGE} || true"
            sh "rm -f ${env.WORKSPACE}/${env.KEY_NAME}.pem"
            deleteDir()
        }
    }
}