pipeline {
    agent any
    
    environment {
        APP_NAME = "nodejs-devops-app"
        REGISTRY_USER = "vinod223"
        // Ensure this credential ID matches what you created in Jenkins
        DOCKER_HUB_CREDS = credentials('docker-hub-creds')
    }

    stages {
        stage('Provision Infrastructure') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                    script {
                        // Capture the public IP for the deployment stage
                        env.TARGET_IP = sh(script: "terraform output -raw public_ip", returnStdout: true).trim()
                        // Extract the private key generated by Terraform
                        sh "terraform output -raw private_key > ../node_app.pem"
                        sh "chmod 400 ../node_app.pem"
                    }
                }
            }
        }

        stage('Security Scan') {
            steps {
                script {
                    echo "Cleaning up disk space to prevent 'No Space Left' errors..."
                    sh "docker system prune -f"
                    
                    echo "Building temporary image for security scanning..."
                    sh "docker build -t ${REGISTRY_USER}/${APP_NAME}:scan ./app"
                    
                    echo "Scanning Image for High/Critical Vulnerabilities..."
                    // We scan the image directly; this covers both OS layers and your Node.js code
                    sh "docker run --rm aquasec/trivy:latest image --severity HIGH,CRITICAL ${REGISTRY_USER}/${APP_NAME}:scan"
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                echo "Tagging and pushing the verified image..."
                sh "docker tag ${REGISTRY_USER}/${APP_NAME}:scan ${REGISTRY_USER}/${APP_NAME}:latest"
                sh "echo ${DOCKER_HUB_CREDS_PSW} | docker login -u ${DOCKER_HUB_CREDS_USR} --password-stdin"
                sh "docker push ${REGISTRY_USER}/${APP_NAME}:latest"
            }
        }

        stage('Deploy to EC2') {
            steps {
                echo "Deploying to ${env.TARGET_IP}..."
                // Using the script from your 'scripts' folder
                sh "bash scripts/deploy.sh ${env.TARGET_IP} ${REGISTRY_USER}/${APP_NAME}:latest"
            }
        }

        stage('Health Check') {
            steps {
                echo "Verifying deployment..."
                sh "curl -f http://${env.TARGET_IP}:3000/health || exit 1"
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace..."
            sh "rm -f node_app.pem"
            cleanWs()
        }
        success {
            echo "Pipeline completed successfully! App is live at http://${env.TARGET_IP}:3000"
        }
        failure {
            echo "Pipeline failed. Check logs for details."
        }
    }
}