#!/bin/bash
TARGET_IP=$1
IMAGE_NAME=$2
# Path to the key generated by Jenkins from Terraform output
KEY_FILE="node_app.pem"

echo "Deploying $IMAGE_NAME to $TARGET_IP..."

ssh -i $KEY_FILE -o StrictHostKeyChecking=no ubuntu@$TARGET_IP << EOF
    sudo docker pull $IMAGE_NAME
    sudo docker stop nodejs_app || true
    sudo docker rm nodejs_app || true
    sudo docker run -d --name nodejs_app -p 3000:3000 $IMAGE_NAME
EOF